"""Validate the canonical CI skills and their generated Claude mirror.

`.agents/skills/` is authored; `.claude/skills/` is generated by
`sync_skills.py`. This check enforces the skill frontmatter contract (name
matches directory, description present, no unresolved placeholders, bounded
size), the fixed skill set, and — like a generated-docs drift check — that the
mirror is byte-identical to the source. It plugs into validate_all via
`check()`.
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = REPO_ROOT / ".agents" / "skills"
MIRROR = REPO_ROOT / ".claude" / "skills"
NAME_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
MARKER = ".generated-from-agents-skills"
EXPECTED_SKILLS = {
    "ci-inventory-audit", "github-actions-authoring", "github-actions-security",
    "ci-free-tier-planner", "ci-failure-triage", "ci-release-provenance",
    "ci-cost-performance", "ci-runtime-contract-testing",
}
PLACEHOLDERS = ("TODO_PLACEHOLDER", "<fill-me>", "TBD_PLACEHOLDER")


def _frontmatter(text: str) -> dict:
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("unterminated YAML frontmatter")
    return yaml.safe_load(text[4:end]) or {}


def check() -> list[str]:
    problems: list[str] = []
    if not CANONICAL.is_dir():
        return [f"missing canonical skill directory: {CANONICAL.relative_to(REPO_ROOT)}"]

    names: list[str] = []
    for skill_dir in sorted(p for p in CANONICAL.iterdir() if p.is_dir()):
        source = skill_dir / "SKILL.md"
        where = f".agents/skills/{skill_dir.name}/SKILL.md"
        if not source.is_file():
            problems.append(f"{where}: missing SKILL.md")
            continue
        text = source.read_text(encoding="utf-8")
        try:
            meta = _frontmatter(text)
        except ValueError as exc:
            problems.append(f"{where}: {exc}")
            continue
        name = meta.get("name")
        description = meta.get("description")
        if name != skill_dir.name:
            problems.append(f"{where}: name must equal directory {skill_dir.name!r}")
        if not isinstance(name, str) or NAME_RE.fullmatch(name) is None:
            problems.append(f"{where}: name must be kebab-case")
        else:
            names.append(name)
        if not isinstance(description, str) or len(description.strip()) < 40:
            problems.append(f"{where}: description must be a substantial string")
        if len(text.splitlines()) > 500:
            problems.append(f"{where}: exceeds the 500-line skill budget")
        for token in PLACEHOLDERS:
            if token in text:
                problems.append(f"{where}: unresolved placeholder {token}")

        mirror = MIRROR / skill_dir.name / "SKILL.md"
        if not mirror.is_file():
            problems.append(
                f".claude/skills/{skill_dir.name}/SKILL.md: missing generated "
                "mirror (run scripts/sync_skills.py)"
            )
            continue
        if hashlib.sha256(source.read_bytes()).digest() != hashlib.sha256(
            mirror.read_bytes()
        ).digest():
            problems.append(
                f".claude/skills/{skill_dir.name}/SKILL.md: mirror drift "
                "(run scripts/sync_skills.py)"
            )
        marker = MIRROR / skill_dir.name / MARKER
        if not marker.is_file():
            problems.append(
                f".claude/skills/{skill_dir.name}/{MARKER}: missing generation marker"
            )

    if len(names) != len(set(names)):
        problems.append("skills: duplicate skill names")
    if set(names) != EXPECTED_SKILLS:
        problems.append(
            f"skills: set mismatch; got {sorted(names)}, expected "
            f"{sorted(EXPECTED_SKILLS)}"
        )

    # No orphan mirror directories left behind by a removed skill.
    if MIRROR.is_dir():
        mirror_names = {p.name for p in MIRROR.iterdir() if p.is_dir()}
        canonical_names = {p.name for p in CANONICAL.iterdir() if p.is_dir()}
        for orphan in sorted(mirror_names - canonical_names):
            problems.append(
                f".claude/skills/{orphan}: mirror has no canonical source "
                "(run scripts/sync_skills.py)"
            )
    return problems


def main() -> int:
    problems = check()
    if problems:
        print("check_skills: FAIL", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    print("check_skills: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
