#!/usr/bin/env python3
"""Generate catalog-derived documentation.

The generated files are intentionally small and reviewable. They prove that
`catalog/` is the source of truth for the high-churn matrices while prose docs
remain human-authored.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "catalog" / "capabilities.yml"
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"
GENERATED_DIR = REPO_ROOT / "docs" / "generated"


def _load_capabilities() -> list[dict[str, Any]]:
    doc = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    return list(doc.get("capabilities", []))


def _availability(value: str) -> str:
    return {
        "free": "free",
        "paid": "paid",
        "unavailable": "unavailable",
        "conditional": "conditional",
        "available": "available",
    }.get(value, value)


def capability_matrix(caps: list[dict[str, Any]]) -> str:
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated capability matrix",
        "",
        "| Capability | Cluster | Status | Public OSS | Private free | Private paid | Workflow | Example |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cap in sorted(caps, key=lambda item: (item["cluster"], item["id"])):
        workflow = cap.get("workflow") or "-"
        example = cap.get("example") or "-"
        lines.append(
            "| {name} (`{id}`) | {cluster} | {status} | {public} | {private_free} | {private_paid} | `{workflow}` | `{example}` |".format(
                name=cap["name"],
                id=cap["id"],
                cluster=cap["cluster"],
                status=cap["status"],
                public=_availability(cap["public_oss"]),
                private_free=_availability(cap["private_free"]),
                private_paid=_availability(cap["private_paid"]),
                workflow=workflow,
                example=example,
            )
        )
    lines.extend(["", "---", "Last generated: 2026-07-08", ""])
    return "\n".join(lines)


def workflow_inventory(caps: list[dict[str, Any]]) -> str:
    by_workflow: dict[str, list[dict[str, Any]]] = {}
    for cap in caps:
        workflow = cap.get("workflow")
        if workflow:
            by_workflow.setdefault(workflow, []).append(cap)
    lines = [
        "<!-- Generated by scripts/generate_docs.py; do not edit by hand. -->",
        "# Generated workflow inventory",
        "",
        "| Workflow | Capability IDs | Statuses |",
        "| --- | --- | --- |",
    ]
    for path in sorted(WORKFLOWS_DIR.glob("*.yml")):
        rel = f".github/workflows/{path.name}"
        if path.name in {"ci.yml", "release.yml"}:
            ids = "internal"
            statuses = "internal"
        else:
            caps_for_workflow = by_workflow.get(rel, [])
            ids = ", ".join(f"`{cap['id']}`" for cap in caps_for_workflow) or "MISSING"
            statuses = ", ".join(sorted({cap["status"] for cap in caps_for_workflow})) or "MISSING"
        lines.append(f"| `{rel}` | {ids} | {statuses} |")
    lines.extend(["", "---", "Last generated: 2026-07-08", ""])
    return "\n".join(lines)


def render() -> dict[Path, str]:
    caps = _load_capabilities()
    return {
        GENERATED_DIR / "capability-matrix.md": capability_matrix(caps),
        GENERATED_DIR / "workflow-inventory.md": workflow_inventory(caps),
    }


def check() -> list[str]:
    stale: list[str] = []
    for path, content in render().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(f"generated doc is stale: {path.relative_to(REPO_ROOT)}")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = parser.parse_args()
    outputs = render()
    if args.check:
        stale = check()
        if stale:
            print("generated docs are stale:")
            for path in stale:
                print(f"  - {path}")
            return 1
        print("generate_docs: OK")
        return 0

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
